### ISSUE TITLE
Using this as a library

### ISSUE THREAD

**Issue by johnroper100** [matthewnau/bitmoji#1]
Hi, I'd like to use this as a library in a web app I'm writing. Is this possible?

**Comment by matthewnau** [comment]
Yes this would definitely be possible. Are you writing your web app in Node.js?

**Comment by johnroper100** [comment]
Yes. I'm actually trying to call it from the ionic framework (angular 5) but I don't think that makes much difference.

**Comment by matthewnau** [comment]
@johnroper100 see if my other repo works better if you're still interested. [Libmoji.](https://github.com/matthewnau/libmoji)

**Comment by johnroper100** [comment]
Ok, thanks
